### ISSUE TITLE
Beta and Release branches

### ISSUE THREAD

**Issue by turbobabr** [skpm/sketch-headers#1]
I think it might be useful to add `beta` branch to push headers for released beta versions as well like it's done here:
https://github.com/abynim/Sketch-Headers/branches

**Comment by turbobabr** [comment]
Please disregard my previous suggestion, I thought this repo is just a plain dump of `*.h` files. :)

**Comment by mathieudutour** [comment]
I though about it but I think the beta should be in the main branch: when we release a sketch version, very few things are going to change from a beta to the actual release. So it’s always better to look at the beta so you have more time to see what’s going to happen
