### ISSUE TITLE
Missing properties

### ISSUE THREAD

**Issue by abynim** [skpm/sketch-headers#13]
Any idea why some properties are missing for a few classes? I don't see a pattern, it just seems random.

For example, `MSLayerArray` has 
```@property(copy, nonatomic) NSArray *layers;``` 
but it's missing in the exported headers.

**Comment by mathieudutour** [comment]
maybe because when the script can't parse a property, it bails out. I'll try to check what's going on

**Comment by mathieudutour** [comment]
Ah it's actually because `layers` is not declared in the `MSLayerArray.h`. It's a private property in `MSLayerArray.m`.

The public API is `containedLayers` coming from `MSLayerContainment`.
